POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "User 6",
  "email": "any6@skynet.com",
  "referrer": "ea8ecffe-8c59-4d05-a529-ed94be941809"
}

###
GET http://localhost:3333/invites/ae3246a5-a861-46d0-b484-75f22d0467d6

###
GET http://localhost:3333/subscribers/ae3246a5-a861-46d0-b484-75f22d0467d6/ranking/clicks

###
GET http://localhost:3333/subscribers/ae3246a5-a861-46d0-b484-75f22d0467d6/ranking/count

###
GET http://localhost:3333/subscribers/ae3246a5-a861-46d0-b484-75f22d0467d6/ranking/position

###
GET http://localhost:3333/ranking


#  "referrer": "ae3246a5-a861-46d0-b484-75f22d0467d6"